### PR TITLE
add theme argument to view in dark mode or light mode

### PR DESCRIPTION
**Pull request by anhtumai**
Theme is option to view mark down file, in light mode or dark mode. Fix https://github.com/joeyespo/grip/issues/358

### CODE REVIEW

**Comment by anhtumai** [comment]
Fix https://github.com/joeyespo/grip/issues/358

**Comment by anhtumai** [comment]
@joeyespo  This is ready for review

**Comment by anhtumai** [comment]
## Explanation for this PR:

At the time this PR is created, [GitHub](https://github.com) uses `dark-color-mode`, `data-light-theme`, and `data-dark-theme` parameters in html tag to specify the theme of the website. This feature is not in any documentation, as far as I know.

image
 
In dark mode, these values are `data-color-mode`: `dark`, `data-light-theme`: `light`, and `data-dark-theme`: `dark`
In light mode, these values are `data-color-mode`: `light`, `data-light-theme`: `light`, and `data-dark-theme`: `dark`

## Additional benefit 
I checked the HTML content of the GitHub website and saw that its styling depends on these parameters.

image

Therefore, even if we don't need it, adding these parameters above to the html tag in our generated HTML file will make the output website prettier and more like GitHub.

## What I do in this PR

- Add `theme` optional argument to the CLI parser, which can either be "light" or "dark" 
- Pass `theme` option to `export` and `render_template` function
- Add `data-color-mode`, `data-dark-theme`, `data-light-theme` to `base.html`
- Fix all the tests with these changes above

**Comment by Potato22** [comment]
Any updates on this getting pulled anytime soon?

**Comment by claudio-ebel** [comment]
After fiddling around over an hour with the standard installation, I
* installed your version with `pip install git+https://github.com/anhtumai/grip.git@358-add-dark-theme`
* used it with `grip --theme=dark /path/to/my/readme.md`
and was so happy to have it working… I hope your pull request gets merged soon!

**Comment by joeyespo** [comment]
Looks good! Thank you for the PR, @anhtumai!

I'll comment back here once a new release is out.

**Comment by Potato22** [comment]
oh my gosh finally!!

**Comment by raytsou** [comment]
@joeyespo Is this ready for release? Would really love to have this feature without cloning the repo.

**Comment by seagle0128** [comment]
Hi there, does this PR work on Windows? I didn't see `--theme` option with `grip 4.6.2` on Windows 11. I installed `grip` via pip3.

**Comment by David-Ongaro** [comment]
I can't see it on macOS `grip 4.6.2` either (installed via Homebrew). A new release including this feature would be nice.

**Pull request merged**
