### PR TITLE
Add Documentation Generation Workflow into Tips section of README.md

### PR DESCRIPTION
**Pull request by mrexmelle**
As discussed in #165 , this pull request is made to provide tips for those who want to generate an HTML-based documentation from markdown files.

### CODE REVIEW

**Comment by joeyespo** [comment]
This is great! Thank you for sharing your documentation process :smile: 

If possible, I'd really like to expose it in a cross-platform way. Do you have the time to translate this to a Python script (minus the `tar` step)? It could even live in a Gist so you can own it and update it as you like. If not, no problem, I'll pull it in as-is and tinker with it later.

**Comment by mrexmelle** [comment]
Hi @joeyespo .

Sure, no problem, I'll share it within the next few days :smile:

**Comment by mrexmelle** [comment]
Hello @joeyespo,

Check this out:
https://gist.github.com/mrexmelle/659abc02ae1295d60647

**Comment by joeyespo** [comment]
Published! (Finally.)

I attempted to simplify the steps slightly. Let me know if it's no good. One enhancement that could simplify them further is if Grip takes `CACHE_DIRECTORY` from a `GRIP_CACHE_DIRECTORY` ENV variable. Then steps 1 and 2 can be combined:

```bash
$ cd YOUR_DIR
$ export GRIPURL=$(pwd)
$ export GRIP_CACHE_DIRECTORY=$(pwd)/assets
```

What do you think?

And thanks for your contributions, @mrexmelle. Much appreciated!

**Comment by mrexmelle** [comment]
This is good! Actually I was kinda stuck thinking about how to simplify the steps of defining the assets directory for the users. This one certainly will do, as well as the one you mention in current README.

You're welcome @joeyespo. The pleasure is mine!

**Pull request merged**
