### PR TITLE
Hiding password prompting in login

### PR DESCRIPTION
**Pull request by mekoda**

### CODE REVIEW

**Comment by mekoda** [comment]
I was going to suggest to verify login right after the user input, but I think the most suitable effort here is to work on issue https://github.com/joeyespo/grip/issues/82 and ensure this too. This will lead to a more responsive experience, in which entering wrong credentials will not even execute anything.

**Comment by mekoda** [comment]
Oh, sure. Working on it.

**Comment by joeyespo** [comment]
Wow, I had no idea about this builtin package. Learn something new every day :smile: 

Thanks for this simple implementation, it looks good :+1:

**Comment by joeyespo** [comment]
> I was going to suggest to verify login right after the user input, but I think the most suitable effort here is to work on issue #82 and ensure this too.

Just noticed this comment. Yeah, that seems fine to defer validation since it's nontrivial. Ready to pull this in once `--pass` is back.

**Comment by mekoda** [comment]
Done.

**Comment by joeyespo** [comment]
Excellent. Thank you, @mekoda! Will release soon.

**Pull request merged**
