### PR TITLE
Patch the GitHub API response to work around the header bug

### LINKED ISSUE #244: Funky headings
I think something in Github’s API must have changed very recently. Sometime in the past day or so my headings started to look like this:

screenshot 2017-09-22 19 45 52

### PR DESCRIPTION
**Pull request by joeyespo**
Fixes #244.

### CODE REVIEW

**Comment by joeyespo** [comment]
Looks like the tests are only failing for Python 2.6.

Merging in. Perhaps it's time to drop 2.6?

**Comment by zmwangx** [comment]
Cool, thanks for the quick fix. Care to cut a release?

**Comment by meyer** [comment]
@joeyespo rad, thanks for the quick turnaround!

**Comment by joeyespo** [comment]
On it!

**Pull request merged**
