### PR TITLE
Added --title option

### PR DESCRIPTION
**Pull request by jlhonora**
Manually set the page's title with `--title=<title>`.

See #110

### CODE REVIEW

**Comment by jlhonora** [comment]
If there's a test suite please let me know to adjust accordingly.

**Comment by joeyespo** [comment]
Look good! Thanks for taking this on, @jlhonora!

**Comment by joeyespo** [comment]
Wow, reviewing this and #119 makes me think it's about time for a refactor. Parameters are adding up! Makes it much more work for collaborators like you to contribute.

**Comment by joeyespo** [comment]
(Just opened #126 to capture that.)

**Comment by jlhonora** [comment]
@joeyespo My exact same thoughts! I'm used to the Ruby on Rails `params` pattern (a single hash with all the parameters in it), but sometimes it feels too loose. I'm very interested to see what you come up with.

Anyways, thanks for the library, it's been of great use to me.

**Comment by joeyespo** [comment]
@jlhonora Yeah, some Node libs use that pattern too. It can be loose indeed. I'll explore some possibilities in a future release.

Thanks :-) Glad you've found it useful.

**Pull request merged**
